language: php

php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3
  - 7.4

install:
  - composer self-update
  - composer global require "fxp/composer-asset-plugin:~1.3"
  - composer install

before_script:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - composer info | sort
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover